jobs:
  ci:
    name: Workflow
    runs-on: ubuntu-20.04

    steps:
      - name: Start Up
        uses: actions/checkout@v2
      - name: Get Deps
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Unit Tests
        run: ./main/build

name: Run

on:
  schedule:
    - cron: "45 */6 * * *"
